# Generated by Django 3.2.5 on 2021-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210715_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productincart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
